"""Adiciona campos admin e etiquetas

Revision ID: f5b1011f35bb
Revises: 
Create Date: 2025-06-25 13:23:44.480828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b1011f35bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corretor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etiquetas', sa.Text(), nullable=True))
        batch_op.alter_column('origem',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('origem',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('etiquetas')

    with op.batch_alter_table('corretor', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
